### ISSUE TITLE
Doesn't work in Heroku & Docker

### ISSUE THREAD

**Issue by JamieREvans** [andremedeiros/ruby-c-cheat-sheet#3]
I just want to start by saying thank you for creating this guide. It's really well written.

I've been able to create, maintain and use a gem following this guide for over a month, now. However, when I deploy my application (which requires this gem) to Heroku (or when I run locally with Docker), it says that it can't load the bundle file:

```
LoadError: cannot load such file -- /tmp/build_1a48d0aa9916920ae50b519fa3b7ef5a/vendor/bundle/ruby/2.6.0/bundler/gems/myawesomegem-6221d7577223/myawesomegem/myawesomegem
```

When I run the application normally using my environment (`OS X` / `unix`), the bundle works as expected and I don't have any issues with my application.

Do you have any idea as to why I'm having this issue? I don't understand what the difference is between my local vs containerized builds.

**Comment by andremedeiros** [comment]
Thank you for the kind words!

I'll have a look! Would you be willing to produce a quick test repo I can use as a reference?

**Comment by JamieREvans** [comment]
Hey. Sorry for the delay. My problem came from including compiled files and not waiting for rake before trying to include the bundle (it was being included in the Gemspec). In docker / heroku, it was looking for a shared objects file (`.so`), which hadn't been built by the time it was included. Sorry for the concern.
